name: Release Windows Executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller assistant_seika_bridge.py --name AssistantSeikaBridge.exe
          pyinstaller show_sound_device.py --name ShowSoundDevice.exe

      - name: Create config.json
        run: copy config.json.template config.json

      - name: Create release archive
        run: |
          $tagName = "${{ github.ref_name }}"
          $zipName = "AssistantSeikaBridge-$tagName.zip"
          Compress-Archive -Path dist\AssistantSeikaBridge.exe\AssistantSeikaBridge.exe, dist\AssistantSeikaBridge.exe\_internal, dist\ShowSoundDevice.exe\ShowSoundDevice.exe, LICENSE, README.md, images, config.json -DestinationPath $zipName

      - name: Upload release archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./AssistantSeikaBridge-${{ github.ref_name }}.zip
          asset_name: AssistantSeikaBridge-${{ github.ref_name }}.zip
          asset_content_type: application/zip
