name: Release Windows Executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --windowed your_script.py # your_script.pyを実際のスクリプト名に置き換えてください

      - name: Create config.json
        run: copy config.json.template config.json

      - name: Create release archive
        run: |
          Compress-Archive -Path dist\your_script.exe, LICENSE, README.md, images, config.json -DestinationPath release.zip

      - name: Upload release archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release.zip
          asset_name: your_release_name.zip # your_release_nameを実際のリリース名に置き換えてください
          asset_content_type: application/zip
